---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yba-operator
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - componentstatuses
  - configmaps
  - daemonsets
  - deployments
  - events
  - endpoints
  - horizontalpodautoscalers
  - ingress
  - jobs
  - limitranges
  - namespaces
  - nodes
  - poddisruptionbudgets
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - secrets
  - serviceaccounts
  - services
  - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "ybaoperator.io"
  resources:
  - adminusers
  - adminusers/status
  - cloudproviders
  - cloudproviders/status
  - universes
  - universes/status
  - softwares
  - softwares/status
  verbs:
  - '*'
