---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yba-operator
  namespace: yba-operator
spec:
  selector:
    matchLabels:
      app: yba-operator
  template:
    metadata:
      labels:
        app: yba-operator
    spec:
      serviceAccountName: yba-operator
      containers:
      - name: operator
        image: ghcr.io/btjimerson/yba-kubernetes-operator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: YBA_HOSTNAME
          value: "yugaware-yugaware-ui.yugabyte.svc.cluster.local"
        - name: YBA_KUBECONFIG_PATH
          value: "/etc/yugabyte-kubeconfig/yba-kubeconfig.yaml"
        - name: YBA_PROVIDER_NAME
          value: "gke"
        - name: YBA_PULL_SECRET_PATH
          value: "/etc/yugabyte-pull-secret/yugabyte-pull-secret.yaml"
        - name: YBA_REGION
          value: "us-central1"
        - name: YBA_REGION_LATITUDE
          value: "41"
        - name: YBA_REGION_LONGITUDE
          value: "-95"
        - name: YBA_ZONE
          value: "us-central1-a"
        volumeMounts:
        - mountPath: /etc/yugabyte-pull-secret
          name: yugabyte-pull-secret
        - mountPath: /etc/yugabyte-kubeconfig
          name: yugabyte-kubeconfig
      volumes:
      - name: yugabyte-pull-secret
        configMap:
          name: yugabyte-pull-secret-config-map
      - name: yugabyte-kubeconfig
        configMap:
          name: yugabyte-kubeconfig-config
