name: build-and-publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
permissions:
  contents: read
  packages: write
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Run tests
      run: mvn test
  publish:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
    - name: Check out main branch
      uses: actions/checkout@v3
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Create distribution
      run: mvn package -DskipTests=true
    - name: Extract metadata for command runner
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=sha
    - name: Build and push command runner
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  